; Note: For bank border tests the sjasmplus generated binary is
; assembled in a special memory mode.
; Instead the slots are generated by the tests:
; 0x0000-0x3FFF:	single banked
; 0x4000-0x7FFF:	multi banked
; 0x8000-0xBFFF:	multi banked
; 0xC000-0xFFFF:	not used


	DEFS 0x0000
SUB_0000:
	NOP
	RET


	DEFS 0x0100-$
	; Simple calls to other banks
	CALL 0x0000		; Found
	CALL 0x4000		; bank border
	CALL 0x8000		; bank border
	CALL 0xC000		; bank border
	RET


	DEFS 0x4000-$
SUB_4000:
	NOP
	RET


	DEFS 0x4100-$
	; Simple calls to other banks
	CALL 0x0000
	CALL 0x4000
	CALL 0x8000
	CALL 0xC000
	RET


	DEFS 0x8000-$
SUB_8000:
	NOP
	RET


	DEFS 0x8100-$
	; Simple calls to other banks
	CALL 0x0000
	CALL 0x4000
	CALL 0x8000
	CALL 0xC000
	RET



; Not assigned test
;....

