; Note: For bank border tests the sjasmplus generated binary is
; assembled in a special memory mode.
; Instead the slots are generated by the tests:
; 0x0000-0x1FFF:	single banked (true)
; 0x2000-0x3FFF:	multi banked (false)
; 0x4000-0x5FFF:	single banked (true)
; 0x6000-0x7FFF:	multi banked (false)
; 0x8000-0xAFFF:	single banked (true)
; 0xA000-0xBFFF:	single banked (true)
; 0xC000-0xFFFF:	single banked (true)


	DEFS 0x1FFE-$
	; Flow through to unassigned or other bank
	LD A,5
	; Flows into a multibank => warning
	NOP

	DEFS 0x3FFE-$
	; Flow through from multi bank to single bank
	LD A,5
	; Is disassembled because it ends in a single bank
	RET

	DEFS 0x5FFF-$
	; Flow through with opcode to unassigned or other bank
	LD A,5
	; Does not matter what follows here


	DEFS 0x7FFF-$
	; Flow through with opcode from multi bank to single bank.
	; This works because other bank is a single bank.
	LD A,5
	; Is disassembled because it ends in a single bank
	RET


	DEFS 0x9FFE-$
	; Flow through single bank to single bank
	LD A,5
	; Is disassembled because it ends in a single bank
	RET


	DEFS 0xAFFE-$
	; Continue in other single bank
	LD A,5
	; Flows into a single bank => no warning
	NOP
	RET


	DEFS 0xBFFF-$
	; Opcode continues in other single bank
	LD A,5
	; Flows into a single bank => no warning
	RET

