
;====================================================

; ZX81 character set
;  ____0___1___2___3___4___5___6___7___8___9___A___B___C___D___E___F____
;  00 SPC GRA GRA GRA GRA GRA GRA GRA GRA GRA GRA  "  GBP  $   :   ?  0F
;  10  (   )   >   <   =   +   -   *   /   ;   ,   .   0   1   2   3  1F
;  20  4   5   6   7   8   9   A   B   C   D   E   F   G   H   I   J  2F
;  30  K   L   M   N   O   P   Q   R   S   T   U   V   W   X   Y   Z  3F

___ equ $00
_c_ equ $00
_QT equ $0B
_CL equ $0e
_OB equ $10
_CB equ $11
_GT equ $12
_LT equ $13
_EQ equ $14
_iEQ equ $94
_PL equ $15
_MN equ $16
_FS equ $18
_SC equ $19
_DT equ $1b
_c0 equ $1c
_c1 equ $1d
_c2 equ $1e
_c3 equ $1f
_c4 equ $20
_c5 equ $21
_c6 equ $22
_c7 equ $23
_c8 equ $24
_c9 equ $25
_cA equ $26
_cB equ $27
_cC equ $28
_cD equ $29
_cE equ $2a
_cF equ $2b
_cG equ $2c
_cH equ $2d
_cI equ $2e
_cJ equ $2f
_cK equ $30
_cL equ $31
_cM equ $32
_cN equ $33
_cO equ $34
_cP equ $35
_cQ equ $36
_cR equ $37
_cS equ $38
_cT equ $39
_cU equ $3a
_cV equ $3b
_cW equ $3c
_cX equ $3d
_cY equ $3e
_cZ equ $3f
_i0 equ $9c
_i1 equ $9d
_i2 equ $9e
_i3 equ $9f
_i4 equ $A0
_i5 equ $A1
_i6 equ $A2
_i7 equ $A3
_i8 equ $A4
_i9 equ $A5
_iA equ $A6
_iB equ $A7
_iC equ $A8
_iD equ $A9
_iE equ $Aa
_iF equ $Ab
_iG equ $Ac
_iH equ $Ad
_iI equ $Ae
_iJ equ $Af
_iK equ $B0
_iL equ $B1
_iM equ $B2
_iN equ $B3
_iO equ $B4
_iP equ $B5
_iQ equ $B6
_iR equ $B7
_iS equ $B8
_iT equ $B9
_iU equ $Ba
_iV equ $Bb
_iW equ $Bc
_iX equ $Bd
_iY equ $Be
_iZ equ $Bf
