
;====================================================

; ZX81 BASIC Tokens

tk_RND	     equ   64	 ;   RND
tk_INKEYS    equ   65	 ;   INKEY$
tk_PI	     equ   66	 ;   PI
tk_DBLQUOTE  equ   192	 ;   ''
tk_AT	     equ   193	 ;   AT
tk_TAB	     equ   194	 ;   TAB
tk_CODE      equ   196	 ;   CODE
tk_VAL	     equ   197	 ;   VAL
tk_LEN	     equ   198	 ;   LEN
tk_SIN	     equ   199	 ;   SIN
tk_COS	     equ   200	 ;   COS
tk_TAN	     equ   201	 ;   TAN
tk_ASN	     equ   202	 ;   ASN
tk_ACS	     equ   203	 ;   ACS
tk_ATN	     equ   204	 ;   ATN
tk_LN	     equ   205	 ;   LN
tk_EXP	     equ   206	 ;   EXP
tk_INT	     equ   207	 ;   INT
tk_SQR	     equ   208	 ;   SQR
tk_SGN	     equ   209	 ;   SGN
tk_ABS	     equ   210	 ;   ABS
tk_PEEK      equ   211	 ;   PEEK
tk_USR	     equ   212	 ;   USR
tk_STRS      equ   213	 ;   STR$
tk_CHRS      equ   214	 ;   CHR$
tk_NOT	     equ   215	 ;   NOT
tk_STARSTAR  equ   216	 ;   **
tk_OR	     equ   217	 ;   OR
tk_AND	     equ   218	 ;   AND
tk_LEQ	     equ   219	 ;   <=
tk_GEQ	     equ   220	 ;   >=
tk_NEQ	     equ   221	 ;   <>
tk_THEN      equ   222	 ;   THEN
tk_TO	     equ   223	 ;   TO
tk_STEP      equ   224	 ;   STEP
tk_LPRINT    equ   225	 ;   LPRINT
tk_LLIST     equ   226	 ;   LLIST
tk_STOP      equ   227	 ;   STOP
tk_SLOW      equ   228	 ;   SLOW
tk_FAST      equ   229	 ;   FAST
tk_NEW	     equ   230	 ;   NEW
tk_SCROLL    equ   231	 ;   SCROLL
tk_CONTINUE  equ   232	 ;   CONTINUE
tk_CONT      equ   232	 ;   CONT
tk_DIM	     equ   233	 ;   DIM
tk_REM	     equ   234	 ;   REM
tk_FOR	     equ   235	 ;   FOR
tk_GO_TO     equ   236	 ;   GO TO
tk_GO_SUB    equ   237	 ;   GO SUB
tk_INPUT     equ   238	 ;   INPUT
tk_LOAD      equ   239	 ;   LOAD
tk_LIST      equ   240	 ;   LIST
tk_LET	     equ   241	 ;   LET
tk_PAUSE     equ   242	 ;   PAUSE
tk_NEXT      equ   243	 ;   NEXT
tk_POKE      equ   244	 ;   POKE
tk_PRINT     equ   245	 ;   PRINT
tk_PLOT      equ   246	 ;   PLOT
tk_RUN	     equ   247	 ;   RUN
tk_SAVE      equ   248	 ;   SAVE
tk_RANDOMIZE equ   249	 ;   RANDOMIZE
tk_RAND      equ   249	 ;   RANDOMIZE
tk_IF	     equ   250	 ;   IF
tk_CLS	     equ   251	 ;   CLS
tk_UNPLOT    equ   252	 ;   UNPLOT
tk_CLEAR     equ   253	 ;   CLEAR
tk_RETURN    equ   254	 ;   RETURN
tk_COPY      equ   255	 ;   COPY
